# https://developer.android.com/tools/variables#set

- name: stat .profile
  ansible.builtin.stat:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.profile"
  register: profile

- name: stat .bash_profile
  ansible.builtin.stat:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bash_profile"
  register: bash_profile

- name: which .profile?
  ansible.builtin.set_fact:
    profile_file:
        - .bashrc
        - "{{ '.profile' if profile.stat.exists else '.bash_profile' if bash_profile.stat.exists }}"

- name: environment variables
  ansible.builtin.blockinfile:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{item}}"
    create: true
    marker_begin: "<Android SDK"
    marker_end: "Android SDK/>"
    block: |
      export ANDROID_HOME={{android_home}}
      export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
  loop: "{{profile_file}}"
