# https://developer.android.com/tools/sdkmanager

- name: create dirs
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  loop:
  - "{{ava_dir}}"

- name: get Official Download
  ansible.builtin.get_url:
    url: "{{download_url}}"
    dest: "{{local_mirror}}/{{file_name}}"
    force: false # is not working!
  when: not (local_mirror + '/' + file_name) is exists # Workaround https://github.com/ansible/ansible/issues/64016#issuecomment-786931909

- name: extract Command line tools only
  ansible.builtin.unarchive:
    src: "{{local_mirror}}/{{file_name}}"
    dest: "{{ava_dir}}/"
    creates: "{{installed_dir}}"

- name: create latest dir
  ansible.builtin.file:
    path: "{{latest}}"
    state: directory

- name: move into latest
  command: "mv {{installed_dir}}/{{item}} {{latest}}/"
  args:
    creates: "{{latest}}/source.properties"
  loop:
  - bin
  - lib
  - source.properties

# - name: install cmdline-tools
#   ansible.builtin.shell: './sdkmanager --install "cmdline-tools;latest"'
#   args:
#     chdir: "{{latest}}/bin"
#     creates: "{{ava_dir}}/.knownPackages"
