---
- hosts: localhost
  vars:
    # Host_vars
    ansible_become_password: u

  roles:
  - role: Android Studio
    tags: [ all ]

  - role: SDK manager
    tags: [ SDK, never ]
# - SDK cache/save
# - SDK cache/restore

  - role: ADB
    tags: [ adb ]
