---
# init is not needed if you're only running on localhost!
- hosts: localhost #, fedora, ubuntu
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
# - SDK cache/restore
  - AndroidStudio
  - SDK manager
  - environment variable
# - SDK cache/save